### ISSUE TITLE
XSubs cannot be regenerated and runs perl from incorrect path

### ISSUE THREAD

**Issue by clignos-bbn** [hurricup/Perl5-IDEA#1162]
After a recent upgrade to the Perl5 plugin, I get the following message every launch of IDEA. However, whenever I try to regenerate `Xsubs` it looks like it looks for the perl executable in the JDK directory:

```
10:34:16 AM XSubs change detected
            It seems that yor XSubs declarations file is absent or outdated.
            We recommend you to regenerate it.
            You may do it any time in Perl5 settings.
10:34:52 AM XSubs deparser report: Cannot run program "/opt/jdk1.8.0_20-x86_64/perl": error=2, No such file or directory
```

Log file attached, running on IC-143.2332.3:
[idea.log.txt](https://github.com/hurricup/Perl5-IDEA/files/259548/idea.log.txt)

**Comment by hurricup** [comment]
Is it Java project with perl as secondary language?

**Comment by clignos-bbn** [comment]
Yes, it is.

**Comment by hurricup** [comment]
Unfortuatelly you can't make this work in current version in proper way. 
There is a ticket for this:
https://github.com/hurricup/Perl5-IDEA/issues/1100
And another one: 
https://github.com/hurricup/Perl5-IDEA/issues/1155

Basically, atm in IDEA you may work with Perl5 properly only if it's project sdk. Other IDEs implented in different way and they using Perl as secondary language.

Atm. problem planned to be fixed in 1.6 release, planned for end of May

**Comment by hurricup** [comment]
But you may do the trick to get rid of XSubs announcement. Change project sdk to perl. Restart idea. Deparse xsubs and change SDK back to Java. Should help.

**Comment by clignos-bbn** [comment]
Thanks, I will try that trick of changing the SDK. I did just now and ran into a separate problem. I'll open an issue for that if I cannot figure it out. Feel free to close this issue.
