### ISSUE TITLE
Get rid of incompatible code (available in IDEA only)

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#265]
At the moment, Camelcade can work [only with IDEA](https://confluence.jetbrains.com/display/IDEADEV/Plugin+Compatibility+with+IntelliJ+Platform+Products). We need to get rid of such classes usage:

Missing in PHPStorm, PyCharm, WebStorm, CLion, RubyMine:
* PerlModuleBuilder
  * com.intellij.ide.util.projectWizard.JavaModuleBuilder
* PerlContentEntriesEditor
  * com.intellij.ide.util.projectWizard.importSources
  * com.intellij.openapi.roots.ui.configuration.JavaContentEntryEditor 
* PerlModuleType
  * com.intellij.ide.util.projectWizard.ProjectJdkForModuleStep
* PerlModuleConfigurationEditorProvider
  * com.intellij.openapi.roots.ui.configuration.ClasspathEditor
* PerlElementDescriptionProvider
  * com.intellij.psi.PsiPackage

Also check module import.

**Comment by VISTALL** [comment]
In WebStorm & PhpStorm, and others - you cant use SdkTable. 

SdkTable class can be resolved, but no UI for SDK setup.

**Comment by chashnikov** [comment]
* To get rid of JavaModuleBuilder you can sub-class its parent class ModuleBuilder directly. Probably you would need to copy some code from JavaModuleBuilder#setupRootModel to your implementation, but I think you don't need the most of it (configuring compiler output, java language level, etc).
* Instead of using JavaContentEntryEditor you may use its parent class ContentEntryEditor. And I don't understand why do you use JavaSourceRootDetectionUtil in PerlContentEntriesEditor at all, it'll scan the added source root for *.java files which doesn't make any sense for perl.
* 'if' clause referring to PsiPackage in PerlElementDescriptionProvider probably can be removed (or replaced by PsiDirectory). PsiPackage describes java package and doesn't make sense for perl. 
* I'm not sure why do you need to 'Dependencies' tab for perl modules by adding ClasspathEditor in PerlModuleConfigurationEditorProvider. ClasspathEditor is java thing, it refers to things like compile/test scopes and JARs files which are java specific. Probably you don't need it in perl at all (or you can create your own perl-specific dependencies editor).
* I don't see an appropriate replacement for ProjectJdkForModuleStep in the platform. Probably we'll move SdkSettingsStep and JdkComboBox to platform, but until it's done you can create a copy of these classes and use them.

**Comment by hurricup** [comment]
Thank you for detailed answer!
Dependencies required to specify lib directory, kinda classes root, which can be not the same as src root.

**Comment by chashnikov** [comment]
If the plugin users just need to specify single lib directory you may create a simple implementation of ModuleElementsEditor with TextFieldWithBrowseButton inside and use it instead of ClasspathEditor.

**Comment by hurricup** [comment]
Multiple lib dirs can be in the project and Perl itself provides few additional.
So libs are sequence of https://github.com/hurricup/Perl5-IDEA/raw/master/images/gettingstarted/sdkadded.png and https://github.com/hurricup/Perl5-IDEA/raw/master/images/gettingstarted/movelibup.png

**Comment by chashnikov** [comment]
Ok, you can use JBList wrapped with ToolbarDecorator then.
