### ISSUE TITLE
Performance quickly degrades with file size growth

### ISSUE THREAD

**Issue by vdudouyt** [hurricup/Perl5-IDEA#476]
Hi Alexandr,

I have recently learned about this module, and found it splendid & incredibly useful for me. The only nuisance is that it's performing poor on big files - such as a 5000+-liner module which is found in my company's app. For an instance, it takes up to 3 seconds on my i3 when I hit 'Enter'. Needless to say, the intelligent completion is also super slow. 

Do I understand right that it incurs from the fact that it is not capable yet of incremental parsing? Is it possible to do something with that (even if it means to add some heurestics)? The default editor which comes with IDEA performs well.

Here is a testing file for your convenience: https://www.dropbox.com/s/cytpwxf98l3o82v/bigfile.pl?dl=0

**Comment by hurricup** [comment]
This is one of the [known issues](https://github.com/hurricup/Perl5-IDEA/wiki/Known-issues)
It's a complex problem caused by many little mistakes i've made. Performance will go better and better, but there is no some single bug i could fix. So atm the only solution - avoid large files.

**Comment by vdudouyt** [comment]
Hi!

Thank you very much for the latest release, I have found that CamelCade is now working much faster. However, it is still very far from Vim or Java support in the same IDE - and is not working comfortable on big projects.

Just wanted to report it.

**Comment by hurricup** [comment]
Well it won't ever be as fast as vim. Just because IDEA is much more complicated system written in Java.
To make it fast as native JB products (if possible), parser need to be rewritten from scratch without any bnf. Not sure i'll ever do it in hobby open-source project. 
Performance should not depend on project size, just current file size. And, recently noticed on  amount of short identifiers in the file. Dunno yet why so. So - split files into smaller. Re-factor $c, $d, $e... variables to something meaningful. It helps.
So some optimizations will be done, but nothing dramatic.
