### ISSUE TITLE
Unable to setup project in Intellij IDEA

### ISSUE THREAD

**Issue by vermapratyush** [hurricup/Perl5-IDEA#675]
Hi,
I am unable to setup the project in Intellij IDEA -14 CE.
The compiler reports numerous missing files like 
* PerlElementTypes
* TokenSet.COMMENT_LINE, COMMENT_BLOCK, HEREDOC, HEREDOC_QQ, HEREDOC_QX, HEREDOC_END
* PsiPerlNamespaceDefinition
* PsiPerlGlobVariable
And a few other classes/interfaces are missing as well.

**Comment by hurricup** [comment]
Make sure that you are using plugin compatible with 14 IDEA. Last compatible version is 1.111
All newer releases requires IDEA 15

**Comment by vermapratyush** [comment]
I am trying to setup the codebase of "this" plugin, so that I can contribute to this project.
While setting up the codebase, the IDE is reporting that the above mentioned files are missing, and they are indeed missing form the project.

**Comment by vermapratyush** [comment]
An example
https://github.com/hurricup/Perl5-IDEA/blob/fefaef3bab6d6b195bb2744bc947739fb5172443/src/com/perl5/lang/perl/idea/generation/handlers/GeneratePerlConstructorActionHandler.java#L30
The code makes reference to 
```
import com.perl5.lang.perl.psi.PsiPerlBlock;
```
However there is not such file named "PsiPerlBlock"

**Comment by hurricup** [comment]
Oh, i see.
In order to participate, you need IDEA 15 with plugins: Plugin DevKit, GrammarKit and PSIviewer (optional but useful) 
and IDEA sources, available here: https://github.com/JetBrains/intellij-community

After setting up an environment, you need to compile bnf files with grammar kit (Perl.bnf and Pod.bnf). This will produce classes you are looking for

**Comment by vermapratyush** [comment]
It works!
Thanks. :)
